- common/pulp_ostree/common/constants.py
- common/pulp_ostree/common/model.py
- common/test/unit/common/test_model.py
- extensions_admin/pulp_ostree/extensions/admin/unit.py
- extensions_admin/test/unit/admin/test_unit.py
- plugins/pulp_ostree/plugins/distributors/steps.py
- plugins/pulp_ostree/plugins/importers/steps.py
- plugins/pulp_ostree/plugins/lib.py
- plugins/test/unit/plugins/distributors/test_steps.py
- plugins/test/unit/plugins/importers/test_steps.py
- plugins/test/unit/plugins/test_lib.py
- plugins/types/ostree.json
https://pulp.plan.io/issues/95
Content unit model changed so that each unit is a branch head instead of a snapshot of the entire repository.  Publishing changed to create a new repository and instead of creating links to files in the *backing* ostree repository, pull-local is used to populate the published repository with only those objects referenced by the branch head commits.  Last, the commit metadata is included which *may* contains fields such as *version* depending on how the trees are composed.
> Each unit is a branch head; Publish using pull-local.

- common/pulp_ostree/common/model.py
- common/test/unit/common/test_model.py
- plugins/pulp_ostree/plugins/distributors/steps.py
- plugins/test/unit/plugins/distributors/test_steps.py
https://pulp.plan.io/issues/855
Store 'created' ISODate on OSTree units.  This is used to sort units for published.  We only want to publish the newest branch version of each branch.  The _id on content units is just a plain UUID and cannot be used for sorting.
> refs:855 - store created ISODate used for sorting during publishing.

- common/pulp_ostree/common/constants.py
- common/pulp_ostree/common/errors.py
- plugins/pulp_ostree/plugins/distributors/steps.py
- plugins/pulp_ostree/plugins/importers/steps.py
- plugins/pulp_ostree/plugins/lib.py
- plugins/test/unit/plugins/distributors/test_steps.py
- plugins/test/unit/plugins/importers/test_steps.py
- plugins/test/unit/plugins/test_lib.py
- pulp-ostree.spec
https://pulp.plan.io/issues/912
This PR is issued against a feature branch because there are outstanding issues documented in the story.  For example: the version of libostree needed here has not yet been packaged and released.
Add support for SSL & GPG options.  This additional functionality required much richer support for configuring the ostree remote.  It also introduced conditions whereby multiple pulp repositories with the same feed (remote) could interfere with each others configuration of that *remote*.  So, this PR also changes things so that each importer creates a temporary ostree remote using the *repo_id* instead of the *remote_id* which really uniquely identifies the upstream.  The temporary ostree remote is created, configured and deleted for each sync.  This ensures that …
> Add support for ssl and gpg options.

- plugins/pulp_ostree/plugins/distributors/steps.py
- plugins/test/unit/plugins/distributors/test_steps.py
I noticed that https://github.com/pulp/pulp_ostree/pull/31 had unit tests that fail for pulp:master. This PR updates the WebPublisher `__init__` to match the super class signature and fixes the tests using the now-available working_dir.
> Fix unit tests that fail against Pulp master

- extensions_admin/pulp_ostree/extensions/admin/cudl.py
- extensions_admin/test/unit/admin/test_cudl.py
closes #1074
https://pulp.plan.io/issues/1074
Issue was only in CLI.
Server side did not have any issues:
- if auto_publish was not specified at all , then in config it was False
- if auto_publish was specified and value was True, then in config it was True
This way work other content types, I specifically checked the rpm repo creation behaviour via API.
> Auto-publish now defaults to true.

- common/pulp_ostree/common/constants.py
- plugins/pulp_ostree/plugins/importers/steps.py
- plugins/pulp_ostree/plugins/lib.py
- plugins/test/unit/plugins/importers/test_steps.py
- plugins/test/unit/plugins/test_lib.py
https://pulp.plan.io/issues/897
Incidental improvements:
- Repository subclass object.
- Add step subclass SaveUnitsStep so counts get updated.
- Ref.path renamed to Ref.name for more correct semantics.
The platform needs to be updated include the scratchpad in the serialized repository.
> Fetch and store remote summary information in repo scratchpad.

- common/pulp_ostree/common/constants.py
- common/pulp_ostree/common/errors.py
- plugins/pulp_ostree/plugins/importers/steps.py
- plugins/test/unit/plugins/importers/test_steps.py
https://pulp.plan.io/issues/1178
The main change here is to change the behavior of having the 'branches' import configuration property either unspecified or None (NULL).  This makes sense because the only use case for pull with no branches would be to refresh the summary information stored in the repository scratchpad.  This can still be done by specifying branches = [] in the configuration override in the sync API call.  I doubt there is a legit use case for actually storing the branches = [].
Other changes:
- pull all references using a single PULL call to the lib.  This is more efficient.
- moving attributes in the Main step to properties.  No point in storing the information twice.
- Making *Summary* it's own step.  This is usually fast but could potentially be long running.  Also, …
> Support pulling all branches

- pulp-ostree.spec
The file ostree.json was removed as part of the mongoengine
conversion. This line should have been removed with it.
ostree.json was removed with https://github.com/pulp/pulp_ostree/commit/76ee063e97a692c27533e75687808437fdae5fb6#diff-0cb394973dd7524ed1f7ffb096ac8a93
> Removes a spec file entry for ostree.json which was removed

- plugins/pulp_ostree/plugins/db/model.py
- plugins/pulp_ostree/plugins/distributors/steps.py
- plugins/test/unit/plugins/distributors/test_steps.py
closes#1351
- renames unit_type_id to _content_type_id
- updates tests so they pass too
> Updates plugin to match platform changes on ContentUnit

- pulp-ostree.spec
Fixes:
```
//usr/lib/pulp/plugins/types/
cp: cannot stat 'plugins/types/*': No such file or directory
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.Tz9qLH (%install)
```
Errors seen in koji.
> Removed types/ directory references.

- plugins/etc/httpd/conf.d/pulp_ostree.conf
https://pulp.plan.io/issues/1496
re #1496
It doesn't seem like the spec file or the pulp-dev.py scripts are installing ostree which I found puzzling.
> Store WSGI scripts in /usr/share/pulp/wsgi instead of /srv.

- common/pulp_ostree/common/errors.py
- plugins/pulp_ostree/plugins/importers/steps.py
- plugins/test/unit/plugins/importers/test_steps.py
Raise PulpCodedException when the `feed_url` is not specified.
> Better handling of sync without feed URL specified.

- plugins/pulp_ostree/plugins/distributors/configuration.py
- plugins/pulp_ostree/plugins/distributors/web.py
- plugins/test/unit/plugins/distributors/test_configuration.py
- plugins/test/unit/plugins/distributors/test_web.py
Checks the relative path of ostree distributors for conflicts.
https://pulp.plan.io/issues/1106
This has minimal updates to the unit tests because they would be mocks that do not add much value. Instead, I have opted to add pulp smash tests. https://github.com/PulpQE/pulp-smash/pull/171
closes #1106
> Ensure unique relative path at validation time

- docs/conf.py
Prior to this fix when building the docs you would see a warning
like:
```
html_static_path entry u'/path/to/pulp_ostree/docs/_static' does not exist
```
https://pulp.plan.io/issues/950
re #950
> Configures Sphinx docs config to not look for static media

- pulp-ostree.spec
closes #1934
https://pulp.plan.io/issues/1934
We will need to carry gnupg as dependency until bz#1342154 and 1342161
are not fixed.
> Add gnupg as dependency

- docs/Makefile
- docs/conf.py
- docs/user-guide/configuration.rst
- docs/user-guide/installation.rst
Intersphinx was preventing the strict mode from being enabled
due to docs being built in a network isolated mock environment.
Intersphinx was also going to break because it is tied
to URLs from ReadTheDocs. Now intersphinx is removed.
Strict Sphinx mode is now enabled.
Links are also updated to point to docs.pulpproject.org
https://pulp.plan.io/issues/2034
re #2034
> Remove intersphinx and enable Strict mode

- plugins/pulp_ostree/plugins/importers/web.py
- plugins/test/unit/plugins/importers/test_web.py
https://pulp.plan.io/issues/2544
The copy was not honoring the `units` specified by the API caller.
> Fix unit copy.

- pulp-ostree.spec
Add provides for python2-* packages.  Fedora downstream packages are
named python2-* and provide python-*.  Upstream needs to mirror this for
dependency resolution to work properly
re #2687
> Add provides for python2-* packages

- pulp-ostree.spec
This is needed because `override_config_options` introduced
in Pulp 2.10 are used in OSTree plugin.
> Bump platform version in specfile

- pulp-ostree.spec
The Source0 currently does not lead to the correct source file.
This updates the spec file and renames the source to what would be
the expected source name.
ref #2784
https://pulp.plan.io/issues/2784
> Update spec files Source0

- plugins/pulp_ostree/plugins/db/model.py
- plugins/pulp_ostree/plugins/distributors/steps.py
- plugins/pulp_ostree/plugins/lib.py
- plugins/pulp_ostree/plugins/migrations/0001_timestamp.py
- plugins/setup.py
- plugins/test/unit/plugins/db/test_model.py
- plugins/test/unit/plugins/distributors/test_steps.py
- plugins/test/unit/plugins/importers/test_steps.py
- plugins/test/unit/plugins/test_lib.py
https://pulp.plan.io/issues/3999
This does not implement the proposed solution 3999.  Instead, it uses the history available in the local ostree repository to determine the available depth and branch HEAD.
> Publish correct branch head and depth.

- README.md
The readme didn't indicate which verison of Pulp it was for. This
clearly marks it as Pulp2.
https://pulp.plan.io/issues/4642
closes #4642
> Clearly mark pulp2 support

- CHANGES/143.bugfix
- pulp_ostree/app/tasks/importing.py
- pulp_ostree/app/tasks/stages.py
- pulp_ostree/app/tasks/synchronizing.py
- pulp_ostree/tests/functional/api/test_import.py
- pulp_ostree/tests/functional/api/test_modify.py
- pulp_ostree/tests/functional/api/test_sync.py
Content is now correctly published at the path specified by a distribution:
```
(pulp) [vagrant@pulp3-source-fedora34 devel]$ pulp ostree distribution create --name dist --base-path ostree-dir/asdf/asdf/here --repository foo
Started background task /pulp/api/v3/tasks/7f96508a-0001-4c3d-ac0c-bde7dea217a7/
.Done.
{
"pulp_href": "/pulp/api/v3/distributions/ostree/ostree/b99be70d-95c9-4e3a-beaa-c38ac0358332/",
"pulp_created": "2021-11-09T09:42:36.493573Z",
"base_path": "ostree-dir/asdf/asdf/here",
"base_url": "http://pulp3-source-fedora34.localhost.example.com/pulp/content/ostree-dir/asdf/asdf/here/",
"content_guard": null,
"pulp_labels": {},
"name": "dist",
"repository": "/pulp/api/v3/repositories/ostree/ostree/d148903b-c938-4ce3-b27c-7b37e6462515/",
"repository_version": null
}
(pulp) …
```
> Publish content at the path specified by a distribution

- CHANGES/140.feature
- docs/workflows/import.rst
- pulp_ostree/app/serializers.py
- pulp_ostree/app/tasks/importing.py
- pulp_ostree/app/tasks/stages.py
- pulp_ostree/app/viewsets.py
- pulp_ostree/tests/functional/api/test_import.py
In this commit, multiple bugs have been addressed - improper order of child commits while creating associations with parent commits, duplicated refs storage, and invalid parent commits traversal.
closes #140
> Retrieve parent commits from child commits directly

- CHANGES/170.feature
- pulp_ostree/app/serializers.py
- pulp_ostree/app/tasks/__init__.py
- pulp_ostree/app/tasks/importing.py
- pulp_ostree/app/viewsets.py
- pulp_ostree/tests/functional/api/test_import.py
As of now, users are required to use separate endpoints for importing
content based on the actual workflow. Those who would like to import
all refs and commits into a repository should use the ``import_all``
endpoint. When the users want to append just a set of commits associated
to a specific ref, they should use the ``import_commits`` endpoint.
closes #170
> Split import workflows into separate endpoints

- CHANGES/269.bugfix
- pulp_ostree/app/tasks/importing.py
- pulp_ostree/app/tasks/stages.py
~- [ ] Generate a summary file when modifying the repository (consider generating the summary before finalizing every new repository version)~
~- [ ] Add a test case~
~- [ ] Document flatpak support~
closes #269
> Generate summary files automatically when importing a repository

- CHANGES/277.bugfix
- pulp_ostree/app/tasks/importing.py
- requirements.txt
> Download existing refs to the workdir when generating summaries 

- CHANGES/289.bugfix
- pulp_ostree/app/tasks/importing.py
In this change, the stage is comparing only sha256 digests between existing and newly added artifacts. Furthermore, the time complexity for the old comparison was O(N^2). With the change, we work with O(2N).
closes #289
> Use a customized version of QueryExistingArtifacts

- pulp_ostree/tests/functional/api/test_import.py
[noissue]
The workflow had to be adjusted because of the breaking change introduced in https://github.com/pulp/pulpcore/pull/4750.
> Make sure a distribution is deleted before a repo version

- CHANGES/324.misc
- pulp_ostree/tests/functional/api/test_filter.py
- pulp_ostree/tests/functional/conftest.py
> Rewrite `test_filter.py` using pytest

- CHANGES/325.misc
- pulp_ostree/tests/functional/api/test_import.py
- pulp_ostree/tests/functional/conftest.py
> Rewrite `test_import.py` using pytest

- functest_requirements.txt
The CI is failing with `pytest-8.0.0`:
```
E   PermissionError: [Errno 13] Permission denied: '/lost+found/__init__.py'
```
[noissue]
> Pin pytest version to avoid CI permission errors

- CHANGES/327.misc
- pulp_ostree/tests/functional/api/test_filter.py
- pulp_ostree/tests/functional/api/test_modify.py
- pulp_ostree/tests/functional/api/test_sync.py
- pulp_ostree/tests/functional/conftest.py
>  Rewrite `test_sync.py` using pytest

- CHANGES/347.doc
- pyproject.toml
- staging_docs/user/guides/00-import-commit.md
- staging_docs/user/guides/01-modify-content.md
- staging_docs/user/tutorials/00-overview.md
- staging_docs/user/tutorials/01-sync-and-host.md
> Migrate the documentation to staging

- CHANGES/373.bugfix
- pulp_ostree/app/tasks/importing.py
- pulp_ostree/app/viewsets.py
- pulp_ostree/tests/functional/api/test_import.py
> Fixes the permission issue with import-all.

- pulp_ostree/tests/functional/api/test_import.py
> Change the repo name on test to avoid collision.
