pulp/pulp_ostree

extensions_admin/pulp_ostree/extensions/admin/cudl.py
This must be merged before https://github.com/pulp/pulp/pull/1703.
=> Fix some imports due to platform PEP-8 changes.

common/pulp_ostree/common/constants.py, extensions_admin/pulp_ostree/extensions/admin/cudl.py, extensions_admin/test/unit/admin/test_cudl.py, plugins/pulp_ostree/plugins/distributors/configuration.py, plugins/test/unit/plugins/distributors/test_configuration.py
https://pulp.plan.io/issues/99
Needed to support entitlement enforcement.
=> Support user defined relative path.

plugins/etc/httpd/conf.d/pulp_ostree.conf
Just needed to update the Apache configuration.
=> refs #99 - support repo auth.

docs/conf.py
=> Updates extlinks and its usages to use redmine

pulp-ostree.spec
https://pulp.plan.io/issues/733
=> update package dependencies.

plugins/pulp_ostree/plugins/importers/steps.py, plugins/test/unit/plugins/importers/test_steps.py
https://pulp.plan.io/issues/856
=> refs:856 - Limit the units created to those listed in the branches list.

plugins/pulp_ostree/plugins/distributors/steps.py, plugins/test/unit/plugins/distributors/test_steps.py
https://pulp.plan.io/issues/855
I decided to factored out the functionality that fetches the units to publish.  This is so that the publisher does not do the pull-local on commits we don't intend to publish (older units).  Also, more modular and easier to test.  Since the number of branches will be pretty small (< 20), I think this still okay memory-wise.
=> refs:855 - Use correct keyword for sorting by _id.

extensions_admin/pulp_ostree/extensions/admin/cudl.py, extensions_admin/test/unit/admin/test_cudl.py, plugins/pulp_ostree/plugins/lib.py
https://pulp.plan.io/issues/911
=> CLI support for SSL and GPG options.

plugins/pulp_ostree/plugins/distributors/web.py, plugins/test/unit/plugins/distributors/test_web.py
closes #1096
https://pulp.plan.io/issues/1096
=> Deleting an OSTree repo results in a TypeError on the server.

plugins/pulp_ostree/plugins/lib.py, plugins/test/unit/plugins/test_lib.py
Reissue of: https://github.com/pulp/pulp_ostree/pull/39 to be merged to 1.0-dev.  This needs to be included in pulp 2.7.
=> Support listing remote references.

common/pulp_ostree/common/model.py, common/test/unit/common/test_model.py
https://pulp.plan.io/issues/1162
=> ref #1162 - replace (.) with (-) in commit metadata keys.

pulp-ostree.spec
Latest upstream release and contains critical bug fixes and required features.
=> Require ostree 2015.8

docs/user-guide/configuration.rst, docs/user-guide/index.rst, docs/user-guide/release-notes/1.0.x.rst, docs/user-guide/release-notes/index.rst
=> 1.0.0 release notes.

docs/user-guide/recipes.rst, plugins/pulp_ostree/plugins/db/model.py, plugins/pulp_ostree/plugins/distributors/steps.py, plugins/pulp_ostree/plugins/distributors/web.py, plugins/pulp_ostree/plugins/importers/steps.py, plugins/pulp_ostree/plugins/importers/web.py, plugins/test/unit/plugins/db/test_model.py, plugins/test/unit/plugins/distributors/test_steps.py, plugins/test/unit/plugins/distributors/test_web.py, plugins/test/unit/plugins/importers/test_steps.py, plugins/test/unit/plugins/importers/test_web.py
I manually tested that sync and publish work with these changes.
=> various fixes, mostly due to changes in platform

common/setup.py, extensions_admin/setup.py, plugins/setup.py, pulp-ostree.spec
=> Do not install tests

common/pulp_ostree/common/errors.py, plugins/pulp_ostree/plugins/importers/steps.py, plugins/test/unit/plugins/importers/test_steps.py
https://pulp.plan.io/issues/1722
Mainly needed to catch GLib.Error raised (including invalid URL) while fetching the summary.
Made other minor improvements while in the code.
=> Better handling of GLib.Error raised when fetching the summary.

.travis.yml, test_requirements.txt
https://pulp.plan.io/issues/2106
=> pin to flake8-2.6.2 for py2.6 support

dist_list.txt
No conflicts occurred during this merge.
=> Merge master to 3.0 dev

plugins/pulp_ostree/plugins/importers/steps.py, plugins/test/unit/plugins/importers/test_steps.py
https://pulp.plan.io/issues/2213
=> Fix proxy URL construction in remote configuration.

common/pulp_ostree/common/constants.py, docs/tech-reference/distributor.rst, docs/tech-reference/importer.rst, plugins/pulp_ostree/plugins/distributors/steps.py, plugins/pulp_ostree/plugins/importers/steps.py, plugins/pulp_ostree/plugins/lib.py, plugins/test/unit/plugins/distributors/test_steps.py, plugins/test/unit/plugins/importers/test_steps.py, plugins/test/unit/plugins/test_lib.py
https://pulp.plan.io/issues/2205
=> Support tree traversal depth.

plugins/setup.py, pulp-dev.py, run-tests.py
closes #2297
https://pulp.plan.io/issues/2297
=> Pulp3: Rewrite shebangs to python3

docs/conf.py, docs/user-guide/release-notes/1.0.x.rst, docs/user-guide/release-notes/1.1.x.rst, docs/user-guide/release-notes/1.2.x.rst
re #2585
https://pulp.plan.io/issues/2585
=> Modify directive name to generate docs correctly using platfrom config

plugins/pulp_ostree/plugins/distributors/configuration.py
https://pulp.plan.io/issues/2769
Requires: https://github.com/pulp/pulp/pull/3034
=> Fix relative path checking.

pulp-ostree.spec
Add obsoletes to spec
refs #[2639](https://pulp.plan.io/issues/2639)
=> Add obsoletes to spec

plugins/pulp_ostree/plugins/importers/steps.py, plugins/test/unit/plugins/importers/test_steps.py
https://pulp.plan.io/issues/3534
Only the `version` metadata field is _semi-standard_ and known to be used.  There are lots of other fields we don't want to store for the following reasons:
- Illegal field names for mongo.  Example: contains dot (.)
- Unsupported values.  Example: MongoDB can only handle up to 8-byte ints
- Large lists of unused data.
- Not standard.
The original philosophy was to support as much metadata as possible but that has turned out to be
problematic and impractical.
=> Fix sync failures caused by unsupported metadata.

docs/user-guide/release-notes/1.3.x.rst
(cherry picked from commit e7fba3542ca1d761ad6537fbe7bf66d23699f8d7)
=> 1.3.1 release notes cherry-pick

docs/workflows/publish.rst, docs/workflows/sync.rst, docs/workflows/upload.rst, pulp_ostree/app/serializers.py, pulp_ostree/app/tasks/synchronizing.py, pulp_ostree/app/viewsets.py
=> Update the template to match the latest pulpcore version

.github/workflows/scripts/before_install.sh, .github/workflows/scripts/install.sh, pyproject.toml, requirements.txt, template_config.yml
=> Pin pulpcore versions

.github/workflows/create-branch.yml, setup.py
=> Consider alpha and beta versions

.bumpversion.cfg, .github/workflows/create-branch.yml
=> Bump the alpha version

.github/workflows/scripts/release.py
=> Specify the redmine project name

CHANGES/.TEMPLATE.rst
=> Remove --- from the towncrier template

docs/workflows/import.rst
=> Add reference to the parent commit

docs/index.rst
=> Add a missing feature entry for the modify endpoint

README.md
=> Fix the CI status badge

requirements.txt
=> Bump the pulpcore version

.ci/ansible/Containerfile.j2
=> Use github container registry instead of docker

docs/installation.rst, docs/workflows/import.rst, docs/workflows/index.rst, docs/workflows/modify.rst, docs/workflows/publish.rst, docs/workflows/sync.rst
=> Update docs to use CLI commands

docs/installation.rst
=> Add a libostree installation requirement

template_config.yml
=> Keep the CI updated since the 2.0 branch

CHANGES/179.doc, docs/workflows/sync.rst
=> Add a paragraph about filtering remote content

docs/index.rst, docs/workflows/import.rst, docs/workflows/index.rst, docs/workflows/modify.rst, docs/workflows/publish.rst, docs/workflows/sync.rst
=> Adjust the command for importing all refs and commits

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/scripts/install.sh, CHANGES/172.feature, pulp_ostree/app/serializers.py, pulp_ostree/app/tasks/importing.py, template_config.yml
=> Add support for third-party storage backends

pulp_ostree/app/serializers.py, pulp_ostree/app/viewsets.py, pulp_ostree/tests/functional/api/test_modify.py, requirements.txt
https://github.com/pulp/pulpcore/commit/b2d65635a250be49fc8893dbd66bf338f09ec6fa
[noissue]
=> Adopt changes from RepositoryAddRemoveContentSerializer

.ci/ansible/Containerfile.j2
=> Change the path to the plugin

.ci/ansible/Containerfile.j2
=> Fix the path to the plugin

.github/workflows/scripts/docs-publisher.py
=> Publish docs as non-GA

.bumpversion.cfg
=> Remove the alpha tag

.bumpversion.cfg
=> Fix missing dot

CHANGES.rst, CHANGES/172.feature, CHANGES/230.feature
=> Add changelog for 2.0.0

setup.py
=> Fix the version classifier

CHANGES/226.bugfix, pulp_ostree/app/tasks/importing.py
=> Allow joining absolute paths

CHANGES/257.bugfix, pulp_ostree/app/models.py
=> Handle duplicates for Summary and Config files

CHANGES/262.bugfix, pulp_ostree/app/models.py, pulp_ostree/app/viewsets.py
=> Fix remotes assignment to repositories and consecutive sync

CHANGES/279.bugfix, pulp_ostree/app/tasks/importing.py
=> Check for existing parent commits in import-all

CHANGES/288.bugfix, pulp_ostree/app/tasks/importing.py
=> Stop overwriting new refs with old ones when copying them

template_config.yml
=> Keep branch 2.1 updated

CHANGES/303.feature, requirements.txt
=> Make compatible with pulpcore 3.40+.

.github/workflows/scripts/post_before_script.sh
=> Install libostree dependencies for GI

template_config.yml
=> Start supporting only 2.2 branch

.github/workflows/pr_checks.yml, template_config.yml
=> Enable the single-commit check

pulp_ostree/tests/functional/api/test_import.py, requirements.txt
=> Update pulpcore upper bounds.

staging_docs/user/guides/00-import-commit.md
=> Make the description of the `repository_name` argument more cear

CHANGES/403.bugfix, pulp_ostree/tests/functional/api/test_import.py
=> Disable the `import_all` test for non admin users.

.github/workflows/scripts/install.sh, CHANGES/422.misc, pulp_ostree/tests/functional/api/test_filter.py, pulp_ostree/tests/functional/api/test_import.py, pulp_ostree/tests/functional/api/test_modify.py, requirements.txt, template_config.yml
=> Prepare pulp_ostree for pulpcore 3.70

.github/workflows/scripts/install.sh, CHANGES/422.misc, pulp_ostree/tests/functional/api/test_filter.py, pulp_ostree/tests/functional/api/test_import.py, pulp_ostree/tests/functional/api/test_modify.py, requirements.txt, template_config.yml
**This is a backport of PR #428.**
=> [PR #428/87c99f7 backport][2.4] Prepare pulp_ostree for pulpcore 3.70

CHANGES/435.misc, pyproject.toml
=> Allow newer PyGObject.
